### ISSUE TITLE
wiki page content does not load

### ISSUE THREAD

**Issue by BerChill** [phproject-plugins/wiki#16]
After a clean install of both phproject and the wiki-plugin I tried to create a wiki page. The creation of the page runs smoothly but when I want to view the page only the title is displayed correctly. A message below the title reads:

500 Internal Server Error
Fatal error: Unsupported operand types

The server runs PHP Version 5.5.32 and MySQL Version 5.1.61 .

php-error-log output: [07-Apr-2016 10:51:31 UTC] PHP Fatal error:  Unsupported operand types in [MyDirectory]/phproject/app/helper/view.php on line 24
[07-Apr-2016 10:51:31 UTC] Fatal error: Unsupported operand types

When I take a look at the wiki_page table via phpMyAdmin the content is there so it was saved correctly. As I am not proficient with php I cannot really tell if this is a problem with my configuration or with the plugin but other, more complex, php-based wikis work on this server. I am happy to provide any specific configuration values upon request. Thank you for any help with this issue.

**Comment by Alanaktion** [comment]
Thanks for such a detailed report! I'll look into what could cause this and I'll let you know what I find.

**Comment by Alanaktion** [comment]
I've got two different fixes for this, both should work fine. Update either the main `phproject` code or the `wiki` code to the latest and the issue should be resolved.

**Comment by BerChill** [comment]
Thank you! It works for me now.
