### ISSUE TITLE
Call to undefined method parseTextile

### ISSUE THREAD

**Issue by ikkez** [phproject-plugins/wiki#2]
after saving, it get 

> 500 Internal Server Error
> Call to undefined method parseTextile()

this comes from `single.html` at `{{ @this->parseTextile(@page.content) }}`.
I suggest to register this function as a filter in index.php, to make it available as
 `{{@page.content | parseTextile }}` just like `parseText`. Maybe you want to review some other methods in your view class helper as well.

**Comment by Alanaktion** [comment]
This plugin hasn't been updated since I removed the `parseTextile()` function from the `View` class, so it should work to just replace it with `{{ @page.content | parseText }}`. I've fixed this in c829da6.
