### ISSUE TITLE
markdown pages

### ISSUE THREAD

**Issue by ikkez** [phproject-plugins/wiki#4]
it would be great to write wiki pages with markdown support. Currently it's just plain html.

**Comment by Alanaktion** [comment]
You should be able to use either Markdown or Textile depending on what's in your `parse.textile` and `parse.markdown` configuration (since fixing #2).

**Comment by ikkez** [comment]
ah great. thank you alan.

**Comment by Alanaktion** [comment]
I've checked on my local installation and Markdown does work properly.
