### ISSUE TITLE
Follow Phproject user permissions

### ISSUE THREAD

**Issue by Alanaktion** [phproject-plugins/wiki#5]
Creating, editing, and deleting wiki pages should be limited in the same way as issues, following the Phproject permissions/ranks.

**Comment by ikkez** [comment]
I also noticed that the wiki is public accessable, even if you are not logged in. I see some server errors in the page footer, but the page contents is fully visible. I'm not sure if it should be public or not (feature or bug?!), at least I was confused about an `Invalid argument supplied for foreach()` error showing up when viewing a wiki page, but not logged in.

**Comment by Alanaktion** [comment]
There probably should be configuration setting to pick whether the wiki is public. I'll likely add that along with these changes.
