### ISSUE TITLE
Page nesting or category separation

### ISSUE THREAD

**Issue by mishoboss** [phproject-plugins/wiki#7]
It would be awesome if we have wiki page nesting (tree structure) or at least category separation. The current flat list of pages is good only for several pages, but complex documentation needs logically separation in order to be readable.

**Comment by mishoboss** [comment]
BTW, I see there is a "parent_id" field in wiki_page and wiki_page_update tables. What it is used for?

**Comment by mishoboss** [comment]
BTW2, I just added a tree wiki structure. I used the already available "parent_id" field. Page lists are indented and the page parent is chosen from a select field. If you are interested in this mod, I can share it. :)

**Comment by saibot2013** [comment]
:+1: that would really be a nice feature! Maybe you could push your code to your fork so we/I could have a look at?

**Comment by mishoboss** [comment]
Here you go: https://github.com/mishoboss/wiki
:)

I've also added a wysiwyg editor to phproject's textareas. It covers the wiki too.
http://www.jqueryscript.net/demo/Full-featured-jQuery-WYSIWYG-Editor-Plugin-wysiwyg-js/
<img width="1155" alt="screen shot 2015-07-24 at 3 43 39 pm" src="https://cloud.githubusercontent.com/assets/1629929/8874571/da9aa066-321a-11e5-980b-1945cd7ba75a.png">

**Comment by saibot2013** [comment]
Some time has passed, but I really like the page nesting - maybe we could add some navigation on the top or left side.

Your WYSIWYG editor integration looks promising! Does it support image uploading? I would be pleased if you could share this integration, too. Many thanks!

**Comment by Alanaktion** [comment]
I've merged @mishoboss's page nesting, with a couple minor changes. I'm still looking into a few other WYSIWYG options right now, but I'll likely be going with one that generates Markdown rather than HTML, mostly just because I like Markdown :smile:
I've opened #8 to track/discuss WYSIWYG options, since that's a separate feature from the page nesting.
